apiVersion: v1
kind: Service
metadata:
  labels:
    run: jekyll
  name: jekyll
  namespace: development
spec:
  type: NodePort
  selector:
    run: jekyll
  ports:
    - protocol: TCP
      nodePort: 30097
      port: 8080
      targetPort: 4000